spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/blog
    username: ${DB_USER:postgres}
    password: ${DB_PASS:366326434}
  flyway:
    out-of-order: true
  jpa:
    show-sql: true


application:
  security:
    signature: ${SIGNATURE:key}
    lifetime: 1d
    github:
      secret: ${GITHUB_SECRET:secret}
      client-id: ${CLIENT_ID:id}